workspace:
  base: /go
  path: src/github.com/uswitch/hermod

pipeline:
  test:
    image: golang:1.18
    commands:
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go test -v -cover $(go list ./...)
  build:
    image: golang:1.18
    commands:
      - make build

  docker-latest-public:
    image: plugins/docker
    repo: quay.io/uswitch/hermod
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: main

  docker-tagged-public:
    image: plugins/docker
    repo: quay.io/uswitch/hermod
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}
    when:
      event: tag

  docker-latest:
    image: plugins/docker
    repo: registry.usw.co/cloud/hermod
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: main

  docker-tagged:
    image: plugins/docker
    repo: registry.usw.co/cloud/hermod
    tags:
      - ${DRONE_TAG}
    when:
      event: tag

  docker-test:
    image: plugins/docker
    when:
      event: push
    repo: registry.usw.co/cloud/hermod
    tags:
      - testing
      - ${DRONE_COMMIT_SHA}
